### ISSUE TITLE
Sending additional options to Screen call

### ISSUE THREAD

**Issue by jrbaudin** [leoilab/react-native-analytics-segment-io#11]
Hi! 
First of all, thanks for a great library!

Question: Would it be possible to send additional information (parameters) to the Screen?
As the Android SDK spec says it would allow ```screen(category, name, properties, options)```

My goal is to _force send_ the **userId** in the options in order to make sure the event is attributed correctly.

I would submit a PR but I'm not really sure how the ...
```javascript
const RNASegmentIO = NativeModules.RNASegmentIO || NativeModules.SegmentModule
```
... works exactly.

Best Regards

**Comment by jrbaudin** [comment]
How about:
```java
@ReactMethod
    public void screen(@Nullable String category, @Nullable String name, @Nullable ReadableMap properties, @Nullable ReadableMap options) {
        Properties segmentProperties = new Properties();
        Options segmentOptions = new Options();

        if (properties != null) {
            segmentProperties.putAll(properties.toHashMap());
        }

        if (options != null) {
            segmentOptions.putAll(options.toHashMap());
        }

        Analytics.with(getReactApplicationContext()).screen(category, name, segmentProperties, segmentOptions);
    }
```

**Comment by kevinpelgrims** [comment]
Hi @jrbaudin . Thanks for the suggestion.

The `options` parameter is used to set up integrations (https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Options.java). Do you want to add the user id to a specific integration?
And do you think we should set the options on all integrations by default, or should we make it more flexible and also take in a map of <string, map> pairs so you can set up every integration separately?

**Comment by jrbaudin** [comment]
Aha, the Segment documentation confuses once again!
I read somewhere that I could overwrite (forcibly add) the ```user_id```, which the SDK should add automatically.
```json
...
"traits": {
    "anonymousId": "f23ff798-96dc-453d-93d0-380b10e046356",
    "userId": "1234"
},
...
"userId": "1234",
...
```
Where **traits** exists within the ```context``` and the other **userId** outside.

The issue I'm trying to fix is that the majority of the Screen-events I receive aren't connected to a **userId** (they only contain an **anonymousId**) so I'm looking into a way of setting the **userId** manually since the SDK seems to fall through.

I'm totally open to the possibility that the issue lies in my implementation but I haven't been able to prove that ...

**Comment by casperstorm** [comment]
Hej @jrbaudin! I'm just jumping into this issue as well.

Did you run `identify()` before calling `screen()` with a unique id? If you did, you should have tied that user to all their actions. Segment uses the `anonymousId` under the hood, so you should just ignore it, if you want to use your own `userId`.

>The identify call specifies a customer identity that you can reference across the customer’s whole lifetime. Every identify call must have a User ID [...]

> [...] Our browser and mobile libraries automatically use Anonymous IDs under the covers to keep track of users as they navigate around your website or app, so you don’t need to worry about them when using those libraries.

[Source](https://segment.com/docs/spec/identify/#identities)

**Comment by jrbaudin** [comment]
@casperstorm Hi! Yes we're running ```identify``` on login and signup which are entrypoints into the app.
And I assumed, as you say, that Segment should handle this but I still see a lot of non-attributed events with just ```anonymousId```

**Comment by casperstorm** [comment]
@jrbaudin – did you find a solution? I don't think this is releated to this wrapper so I'll close this issue now. If you have any other questions or issues just ask away, or re-open this :)

**Comment by jrbaudin** [comment]
@casperstorm I did not find a solution _per se_ and I agree it's not related to this project. What we do now is to rely less on client tracking by complementing with sending server side events from API and such. I also send many more **identify**-events from the app so the client side SDK should have an active user available at all times. 

Anyways thanks again for a great project!
