### ISSUE TITLE
Tracking before setup can lead to app crashes

### ISSUE THREAD

**Issue by esbenvb** [leoilab/react-native-analytics-segment-io#25]
Calling `track()`, `screen()` etc. before calling `setup()`, might lead to an app crash, due to an uncaught exception thrown by the native Segment module.

We might need a way to handle this.

**Comment by kevinpelgrims** [comment]
This is not a bug, but expected behavior. However, we concluded that there might be a nicer solution in #23

**Comment by esbenvb** [comment]
> This is not a bug, but expected behavior

As an RN developer, I wouldn't expect any npm packages to crash the native app, but let's just call it an enhancement then :)
