### ISSUE TITLE
Linking from dead projects...

### ISSUE THREAD

**Issue by cridenour** [leoilab/react-native-analytics-segment-io#32]
I've been maintaining my own fork of `react-native-segment-io-analytics` with Android support for over a year now. Finally took the time to search for updated libraries and was excited to see this. 

Figured I would help others find it and increase your google-fu with [this PR](https://github.com/smore-inc/react-native-segment-io-analytics/pull/36). 

Any other dead RN-segment projects (specifically ones with native tie ins) that we should try and get pointed here?

**Comment by casperstorm** [comment]
What a great idea, @cridenour 👏 🥇

**Comment by wprater** [comment]
this was a great find, which I found from a cross post! thanks!

@casperstorm is `3.1` a release ready for public?  I see many changes, but it was not tagged as the latest release.

**Comment by romainbriche** [comment]
@wprater `3.1.0` has already been released  https://www.npmjs.com/package/react-native-analytics-segment-io
The changes that occured since are more `README` adjustments.

>  it was not tagged as the latest release
Where did you see this?

**Comment by romainbriche** [comment]
My bad I only tagged it and didn't make a GitHub release. We are planning to improve our release process and include a proper changelog

**Comment by romainbriche** [comment]
> this was a great find, which I found from a cross post! thanks!

@wprater would you mind sharing that cross post? We are thinking about approaching Segment to suggest them to be considered as a recognised unofficial React Native SDK. Such post might help us :)

**Comment by wprater** [comment]
> My bad I only tagged it and didn't make a GitHub release. We are planning to improve our release process and include a proper changelog

no worries here!

**Comment by wprater** [comment]
> @wprater would you mind sharing that cross post? We are thinking about approaching Segment to suggest them to be considered as a recognised unofficial React Native SDK. Such post might help us :)

great idea!  it was the PR linked to from this issue :)

**Comment by Lastin** [comment]
I would recommend trying to point people using this https://github.com/charlires/react-native-segment-analytics here.

**Comment by romainbriche** [comment]
Thank you for the support. We will close this issue for now
