### ISSUE TITLE
Integrate Intercom

### ISSUE THREAD

**Issue by luisfmsouza** [leoilab/react-native-analytics-segment-io#33]
Is it possible to integrate [Segment-Intercom](https://github.com/segment-integrations/analytics-ios-integration-intercom) with this package?

**Comment by kevinpelgrims** [comment]
That is certainly possible.
It is not currently on our roadmap, but would you be up for doing the integration, @luisfmsouza ?

**Comment by luisfmsouza** [comment]
For sure!

I'm coming from the JS world to mobile, so I don't have that much experience with objective-c/swift. But I'll give it a try.

**Comment by romainbriche** [comment]
Awesome @luisfmsouza. Feel free to use this PR as an inspiration https://github.com/leoilab/react-native-analytics-segment-io/pull/21/files
Small note: we like to sort the integration by package name :)
