### ISSUE TITLE
RN 0.51 - Xcode build/import errors

### ISSUE THREAD

**Issue by wanytprograms** [leoilab/react-native-analytics-segment-io#35]
Thank you all for working on react-native-analytics-segment-io! I've been running into build errors in Xcode when trying to build a project with Segment pods.

My podfile has ```use_frameworks! ``` and contains the following pods:
```
pod 'Analytics'
pod 'Segment-Amplitude'
```
When I try to build the project in release or debug, I get the following error:
```
...
In file included from ...[my project_directory]/node_modules/react-native-analytics-segment-io/ios/RNAnalyticsSegmentIO/RNASegmentIO.m:25:
In file included from ...[my project_directory]/node_modules/react-native-analytics-segment-io/ios/RNAnalyticsSegmentIO/RNAIntegrations.h:63:
../../../ios/Pods/Segment-Amplitude/Pod/Classes/SEGAmplitudeIntegrationFactory.h:2:9: fatal error: 'Analytics/SEGIntegrationFactory.h' file not found
#import <Analytics/SEGIntegrationFactory.h>
'Analytics/SEGIntegrationFactory.h' file not found
```
It looks like the Segment-Amplitude files are not able to access the Analytics files. Could there be a linking step that I'm missing?

Could it be related to #9 ?

**Comment by romainbriche** [comment]
Hi @wanytprograms when using the `use_frameworks!` the setup is slightly different. Let me document it in the `README` for you

**Comment by romainbriche** [comment]
@wanytprograms have a look here https://github.com/leoilab/react-native-analytics-segment-io/tree/use-frameworks#ensure-build-order

Hopefully it will fix your problem 🤞

**Comment by wanytprograms** [comment]
@romainbriche - Your instructions on the build order worked! Thank you!

**Comment by romainbriche** [comment]
Great. Glad to hear. I will close this issue once the pending pull request #36 is merged to the `master` branch.

**Comment by benevbright** [comment]
Hey, 
In my case, I have `React` in the Podfile. 
Do you have any idea get it to work in this case?
Since this module doesn't have `podspec`, It's really hard to get it working.
