### ISSUE TITLE
Intercom support for Android - more configuration needed?

### ISSUE THREAD

**Issue by localredhead** [leoilab/react-native-analytics-segment-io#42]
Hello, I attempted to implement this for Android but no matter what I try to do the information that comes through segment shows:
``` 
"integrations": {
    "Intercom": false
  },
```

I am not sure what I need to do in order to have Intercom functional.   Nothing I know of is explicitly setting this to false.  I've included the appropriate `com.segment.analytics.android.integrations:intercom:1.1.0-beta` in the build.gradle.

Am I missing something obvious to get intercom working on Android?

**Comment by romainbriche** [comment]
Hi @localredhead, this is the expected behaviour when using client-side integrations.

In a nutshell what this means is that the info sent to `Segment` shouldn't be sent to `Intercom` via their server-side integration.
Instead `Segment` will use `Intercom`'s SDK to send the desired data to `Intercom`.

**Comment by romainbriche** [comment]
@localredhead have you tried to see if you are receiving the data into `Intercom`?
If not I recommend checking what is happening in `logcat` https://github.com/intercom/intercom-android/blob/master/samples/README.md#troubleshooting

**Comment by cem2ran** [comment]
Might be issue with upstream dependency, as I'm getting the following trying to work `react-native-analytics-segment-io/android`:
```
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompileCopy'.
   > Could not find io.intercom.android:intercom-sdk-base:4.1.2.
     Required by:
         project : > com.segment.analytics.android.integrations:intercom:1.1.0-beta
   > Could not find io.intercom.android:intercom-sdk-fcm:4.1.2.
     Required by:
         project : > com.segment.analytics.android.integrations:intercom:1.1.0-beta

```

**Comment by localredhead** [comment]
@romainbriche forgive my naiveté, is the native https://github.com/intercom/intercom-android a requirement for this library?
