### ISSUE TITLE
Flurry for Android

### ISSUE THREAD

**Issue by pcooney10** [leoilab/react-native-analytics-segment-io#62]
Hey, thanks for making this !

I noticed Flurry is supported for iOS but not Android, but I see a [`analytics-android-integration-flurry`](https://github.com/segment-integrations/analytics-android-integration-flurry) library on the [`segment-integrations`](https://github.com/segment-integrations) account.

Is there a reason this isn't implemented, or can I create a PR like #21 adding a few lines to `build.gradle` and `SegmentModule.java`?

**Comment by kevinpelgrims** [comment]
Flurry was just never added. There's no specific reason for it.
A PR would be welcome!

**Comment by kevinpelgrims** [comment]
Solved with #63
