### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by rhussmann** [leoilab/react-native-analytics-segment-io#70]
Hello!

I've noticed Typescript definitions have been added to this project, but a new version hasn't been published. Would you please publish a version of this package so the typescript definitions can make it out to NPM?

**Comment by CodyBrouwers** [comment]
Just following up on this, would be great to have the definitions in a new version!

**Comment by jtart** [comment]
Is it possible to get a new release out?

**Comment by mla310** [comment]
the latest version has the typescript definitions included
