### ISSUE TITLE
identify: cannot unset a trait

### ISSUE THREAD

**Issue by twelve17** [leoilab/react-native-analytics-segment-io#86]
It seems there is no way to unset a trait via `identify`.  If you send `null` or `undefined` as the value, the library seems to be sending whatever is in the internal storage.

I found this out by accident because I accidentally set a birthday to an object value, which makes the android app using this library crash:

```
08-19 22:37:29.625 25175 25175 E AndroidRuntime: java.lang.RuntimeException: Not an RFC 3339 date: {month=null, day=null, year=null}
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.internal.Iso8601Utils.parse(Iso8601Utils.java:224)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.internal.Utils.parseISO8601Date(Utils.java:109)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.internal.Utils.toISO8601Date(Utils.java:114)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.Traits.birthday(Traits.java:168)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.android.integrations.appboy.AppboyIntegration.identify(AppboyIntegration.java:119)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.IntegrationOperation$8.run(IntegrationOperation.java:162)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.Analytics.performRun(Analytics.java:1421)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.segment.analytics.Analytics$9.run(Analytics.java:782)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-19 22:37:29.625 25175 25175 E AndroidRuntime: Caused by: java.lang.NumberFormatException: Invalid number: {mon
```

From this point forward, the app will crash when any `identify()` call is made. I am unable to fix the bad data due to the inability to unset a trait.  

The only alternative I see is to call `reset()`, but I don't have a reliably way to just call this once without adding special logic in my app to only call this once, and I don't want to repeatedly call `reset()` because that would reset the anonymousId.

Is there another possibility?

**Comment by kevinpelgrims** [comment]
This seems to be an issue in the Segment library itself, not this React Native wrapper. I can see in the code that it expects the `Date` to not be `null`. (See [Traits.java](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Traits.java#L160-L172) and [Iso8601Utils.java](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/internal/Iso8601Utils.java) for details.)
I can't find a good way of unsetting traits in the documentation for the native libraries, only for the [web (javascript) version](https://segment.com/docs/sources/website/analytics.js/#clearing-traits).
Perhaps you should get in touch with their support and see if they have any advice.

**Comment by twelve17** [comment]
Ok, thanks @kevinpelgrims , will do.
