### ISSUE TITLE
Getting an error trying to link with v49.3 of RN

### ISSUE THREAD

**Issue by ericlewis** [leoilab/react-native-analytics-segment-io#9]
/Users/user/work/project/node_modules/react-native-analytics-segment-io/ios/RNAnalyticsSegmentIO/RNASegmentIO.m:8:9: 'Analytics/SEGAnalytics.h' file not found

following the directions doesn't work when I try to build.

**Comment by kasperkronborg** [comment]
Is this happening on both iOS and Android? Have you remembered to depend on the Analytics framework in both your Podfile and in gradle?

**Comment by ericlewis** [comment]
iOS only. Pod file is installed but it appears that the linked React Native analyst ifs lib isn’t able to access the official lib.

**Comment by casperstorm** [comment]
Hi @ericlewis,
We have just merged #13 into master which will fix your problem. @romainbriche has done an incredible job to solve this issue, which turned out to be quite a rabbit hole.
